### ISSUE TITLE
Wrong Query for arrays

### ISSUE THREAD

**Issue by Johnson444** [thomas4019/mongo-query-to-postgres-jsonb#9]
Here is a Mongo Playground: https://mongoplayground.net/p/RBPQcxgT04z

In MongoDB i can filter an array like this `"phones.phone": "222"`

```
db.collection.find({
  $or: [
    {
      name: "John",
      
    },
    {
      name: "Lucy"
    }
  ],
  "phones.phone": "222"
})
```

if I try to run the same in postgres it produces this code:

```
const query = {
  $or: [{ name: "John" }, { name: "Lucy" }],
  "phones.phone": "222",
}

((meta @> '{ "name": "John" }' OR meta @> '{ "name": "Lucy" }') and meta @> '{ "phones": { "phone": "222" } }')
```

This doesn't work as the the phone must be in brackets: `meta @> '{ "phones": [{ "phone": "222" } ]}')`

**Comment by thomas4019** [comment]
@Johnson444 Thanks for trying out the tool. Unfortunately MongoDB has ambiguity here since `phones.phone` supports both an array and a simple nested object. This tool lets you manually specify field paths that are arrays so it can create proper queries for those fields see [this example](https://github.com/thomas4019/mongo-query-to-postgres-jsonb#advanced-select-match-a-field-without-specifying-array-index). It would also be possible in theory to do this for every dotted field path, but then it would make the queries substantially more complicated and less efficient so I'm not sure that's worth the tradeoff

**Comment by Johnson444** [comment]
Thanks, I have seen this chapter before but didn't understand what it does :D I thought it's kind of a sub query, to further filter on previous results :-P

I see your points, but it seems you anyway check for objects first. So it would just make the query longer but shouldn't increase performance, Or do I miss anything ?

`(meta @> '{ "phones": { "phone": "222" } }' OR EXISTS (SELECT * FROM jsonb_array_elements(meta->'phones') WHERE jsonb_typeof(meta->'phones')='array' AND value @> '{ "phone": "222" }')))`

**Comment by thomas4019** [comment]
@Johnson444 Good idea, I've added the ability to pass in the boolean true as the third param to signify all fields should be treated as potential arrays. I also updated the docs about this.
